In [24]:
import pandas as pd

In [25]:
#Loading the data in dataframe
df1 = pd.read_excel('supplier_data_1.xlsx')
df2 = pd.read_excel('supplier_data_2.xlsx')

# Exploring Dataframes

In [26]:
df1.columns

Index(['Werksgüte', 'Bestellgütentext', 'Nenndicke NNN.NN mm mit Dezimalpunkt',
       'Breite', 'Länge', 'Gewicht (kg)', 'Cluster', 'Si-Gehalt', 'Mn-Gehalt',
       'P-Gehalt', 'S-Gehalt', 'Cr-Gehalt', 'Ni-Gehalt', 'Mo-Gehalt',
       'V-Gehalt', 'Cu-Gehalt', 'Nb-Gehalt', 'Ti-Gehalt', 'Al-Gehalt',
       'B-Gehalt', 'Streckgrenze', 'Zugfestigkeit', 'Dehnung'],
      dtype='object')

In [27]:
df2.columns

Index(['PRODUCT_TYPE', 'ORDER_ID', 'SITE', 'MATERIAL_NAME', 'MATERIAL_NUMBER',
       'MATERIAL_QUALITY_NORM', 'SURFACE_COATING', 'DEFECT_NOTES',
       'NOMINAL_THICKNESS_MM', 'WIDTH_MM', 'LENGTH_MM', 'HEIGHT_MM',
       'MASS_MIN_KG', 'NUMBER_OF_COILS', 'DELIVERY_EARLIEST',
       'DELIVERY_LATEST', 'INCO_TERM', 'BUY_NOW_EUR_PER_TON',
       'MIN/MAX_BID_EUR_PER_TON', 'CO2_PER_TON_MAX_KG', 'VALID_UNTIL'],
      dtype='object')

# Deciding Column names

Presently as we see both sheets have column name in different language so the first step would be to choose common lang and naming convention

In [28]:
column_mapping = {
    'Werksgüte': 'FACTORY_QUALITY',
    'Bestellgütentext': 'ORDER_GRADE_TEXT',
    'Nenndicke NNN.NN mm mit Dezimalpunkt': 'NOMINAL_THICKNESS_MM',
    'Breite': 'WIDTH_MM',
    'Länge': 'LENGTH_MM',
    'Gewicht (kg)': 'MASS_MIN_KG',
    'Cluster': 'CLUSTER',
    'Si-Gehalt': 'SI_CONTENT',
    'Mn-Gehalt': 'MN_CONTENT',
    'P-Gehalt': 'P_CONTENT',
    'S-Gehalt': 'S_CONTENT',
    'Cr-Gehalt': 'CR_CONTENT',
    'Ni-Gehalt': 'NI_CONTENT',
    'Mo-Gehalt': 'MO_CONTENT',
    'V-Gehalt': 'V_CONTENT',
    'Cu-Gehalt': 'CU_CONTENT',
    'Nb-Gehalt': 'NB_CONTENT',
    'Ti-Gehalt': 'TI_CONTENT',
    'Al-Gehalt': 'AL_CONTENT',
    'B-Gehalt': 'B_CONTENT',
    'Streckgrenze': 'YIELD_STRENGTH',
    'Zugfestigkeit': 'TENSILE_STRENGTH',
    'Dehnung': 'ELONGATION'
}

df1 = df1.rename(columns=column_mapping)

In [29]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FACTORY_QUALITY       66 non-null     object
 1   ORDER_GRADE_TEXT      70 non-null     object
 2   NOMINAL_THICKNESS_MM  86 non-null     int64
 3   WIDTH_MM              86 non-null     object
 4   LENGTH_MM             86 non-null     float64
 5   MASS_MIN_KG           86 non-null     float64
 6   CLUSTER               74 non-null     object
 7   SI_CONTENT            55 non-null     object
 8   MN_CONTENT            55 non-null     object
 9   P_CONTENT             55 non-null     object
 10  S_CONTENT             48 non-null     object
 11  CR_CONTENT            55 non-null     object
 12  NI_CONTENT            47 non-null     object
 13  MO_CONTENT            48 non-null     object
 14  V_CONTENT             48 non-null     float64
 15  CU_CONTENT            48 non-null     float64
 16  NB_CONTENT            48 non-null     float64
 17  TI_CONTENT            48 non-null     float64
 18  AL_CONTENT            48 non-null     float64
 19  B_CONTENT             48 non-null     float64
 20  YIELD_STRENGTH        48 non-null     float64
 21  TENSILE_STRENGTH      48 non-null     float64
 22  ELONGATION            48 non-null     float64
dtypes: float64(11), int64(1), object(11)
memory usage: 15.6+ KB

In [30]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PRODUCT_TYPE             118 non-null    object
 1   ORDER_ID                 136 non-null    int64
 2   SITE                     136 non-null    object
 3   MATERIAL_NAME            116 non-null    object
 4   MATERIAL_NUMBER          91 non-null     float64
 5   MATERIAL_QUALITY_NORM    119 non-null    object
 6   SURFACE_COATING          0 non-null      float64
 7   DEFECT_NOTES             116 non-null    object
 8   NOMINAL_THICKNESS_MM     136 non-null    float64
 9   WIDTH_MM                 136 non-null    int64
 10  LENGTH_MM                55 non-null     float64
 11  HEIGHT_MM                0 non-null      float64
 12  MASS_MIN_KG              136 non-null    int64
 13  NUMBER_OF_COILS          0 non-null      float64
 14  DELIVERY_EARLIEST        0 non-null      float64
 15  DELIVERY_LATEST          0 non-null      float64
 16  INCO_TERM                108 non-null    object
 17  BUY_NOW_EUR_PER_TON      39 non-null     float64
 18  MIN/MAX_BID_EUR_PER_TON  125 non-null    float64
 19  CO2_PER_TON_MAX_KG       0 non-null      float64
 20  VALID_UNTIL              136 non-null    object
dtypes: float64(11), int64(3), object(7)
memory usage: 22.4+ KB

# Removing column which doesnt have any values

Above we can see the result of df2.info(). There are columns which do not have and value for example see data line number 6, 13, 14 and so on.

In [31]:
empty_columns = df2.columns[df2.isna().all()].tolist()
df2 = df2.drop(columns=empty_columns)

In [32]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PRODUCT_TYPE             118 non-null    object
 1   ORDER_ID                 136 non-null    int64
 2   SITE                     136 non-null    object
 3   MATERIAL_NAME            116 non-null    object
 4   MATERIAL_NUMBER          91 non-null     float64
 5   MATERIAL_QUALITY_NORM    119 non-null    object
 6   DEFECT_NOTES             116 non-null    object
 7   NOMINAL_THICKNESS_MM     136 non-null    float64
 8   WIDTH_MM                 136 non-null    int64
 9   LENGTH_MM                55 non-null     float64
 10  MASS_MIN_KG              136 non-null    int64
 11  INCO_TERM                108 non-null    object
 12  BUY_NOW_EUR_PER_TON      39 non-null     float64
 13  MIN/MAX_BID_EUR_PER_TON  125 non-null    float64
 14  VALID_UNTIL              136 non-null    object
dtypes: float64(5), int64(3), object(7)
memory usage: 16.1+ KB

# Common columns should have same data type

From above df2.info() and df1.info() we can see that only 4 columns match those are

['NOMINAL_THICKNESS_MM', 'WIDTH_MM', 'LENGTH_MM', 'MASS_MIN_KG']

In [33]:
df1.WIDTH_MM=df1.WIDTH_MM.str.replace(',', '')
df1.WIDTH_MM=df1.WIDTH_MM.astype('float64')

In [34]:
df1.NOMINAL_THICKNESS_MM=df1.NOMINAL_THICKNESS_MM.astype('float64')

In [35]:
df2.MASS_MIN_KG=df2.MASS_MIN_KG.astype('float64')

In [36]:
df2.WIDTH_MM=df2.WIDTH_MM.astype('float64')

# Lets see what's inside df's

In [37]:
df1.head()

,FACTORY_QUALITY,ORDER_GRADE_TEXT,NOMINAL_THICKNESS_MM,WIDTH_MM,LENGTH_MM,MASS_MIN_KG,CLUSTER,SI_CONTENT,MN_CONTENT,P_CONTENT,...,MO_CONTENT,V_CONTENT,CU_CONTENT,NB_CONTENT,TI_CONTENT,AL_CONTENT,B_CONTENT,YIELD_STRENGTH,TENSILE_STRENGTH,ELONGATION
0,G2UB5,SZBS800,320.0,856.0,787.0,16.490,WB-G,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,G2UJ5,SZBS800,339.0,918.0,707.0,17.160,WB-G,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C3318,LICRO 500,452.0,1839.0,300.0,18.700,WB-U,0.2540,1.2780,0.0080,...,0.0090,20.0,290.0,12.0,320.0,320.0,25.0,0.0,0.0,0.0
3,C3U15,S380MC mod. 4,532.0,1160.0,461.0,22.011,WB-U,0.2250,1.0630,0.0100,...,0.0060,30.0,150.0,320.0,989.0,430.0,1.0,0.0,0.0,0.0
4,G3UB5,SZBE800,451.0,727.2,557.0,14.020,Spaltband,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df2.head()

,PRODUCT_TYPE,ORDER_ID,SITE,MATERIAL_NAME,MATERIAL_NUMBER,MATERIAL_QUALITY_NORM,DEFECT_NOTES,NOMINAL_THICKNESS_MM,WIDTH_MM,LENGTH_MM,MASS_MIN_KG,INCO_TERM,BUY_NOW_EUR_PER_TON,MIN/MAX_BID_EUR_PER_TON,VALID_UNTIL
0,SHEET,436765,1 company gmbh,S235JR,1.0038,DIN EN 10025,DEKL-S235JR / D2A EID,11.859,1509.0,3008.0,2091.0,FCA,600.0,NaN,20/02/2025 11:00
1,SHEET,436754,1 company gmbh,S355MC,1.0976,DIN EN 10149,NaN,8.057,1011.0,2355.0,2411.0,FCA,600.0,NaN,20/02/2025 11:00
2,SHEET,436755,1 company gmbh,NaN,1.0976,DIN EN 10149,DEKL-S355MC / D2A WEH,8.057,1010.0,2356.0,2251.0,FKA,600.0,NaN,2025-02-20 11:00
3,SHEET,436757,1 company gmbh,S355MC,1.0976,NaN,DEKL-S355MC / D2A WEH,8.057,1011.0,2356.0,2401.0,FCA,600.0,NaN,2025-02-20 11:00
4,SHEET,436758,1 company gmbh,S355MC,1.0976,DN EN 10149,DEKL-S355MC / D2A WEH,8.057,1010.0,2356.0,2401.0,FCA,600.0,NaN,2025-02-20 11:00

In [39]:
df2.VALID_UNTIL.unique()

array(['20/02/2025 11:00', '2025-02-20 11:00', '2025-02-25 16:00',
       '25/02/2025 16:00', '2025-02-21 11:00', '21/02/2025 11:00',
       '2025-02-20 16:00', '20/02/2025 16:00'], dtype=object)

In [40]:
df2.VALID_UNTIL.value_counts(dropna=False)

VALID_UNTIL
2025-02-21 11:00    53
2025-02-20 11:00    35
2025-02-20 16:00    26
2025-02-25 16:00    12
20/02/2025 11:00     4
25/02/2025 16:00     3
21/02/2025 11:00     2
20/02/2025 16:00     1
Name: count, dtype: int64

# Converting object data type to Date and time type.

In [20]:
# df2['VALID_UNTIL'] = df2['VALID_UNTIL'].astype(str).str.strip()
# df2['VALID_UNTIL'] = pd.to_datetime(df2['VALID_UNTIL'], dayfirst=True, errors='coerce')
# df2.VALID_UNTIL.value_counts(dropna=False)

VALID_UNTIL
NaT                    126
2025-02-20 11:00:00      4
2025-02-25 16:00:00      3
2025-02-21 11:00:00      2
2025-02-20 16:00:00      1
Name: count, dtype: int64

# Applying Custom function to convert datatype to datetime

Tried various alterations but the inbuild pd.to_datetime method is unable to convert effectively.

In [41]:
def parse_date(date_str):
    if pd.isna(date_str) or date_str == '':
        return pd.NaT
    formats = [
        '%Y-%m-%d %H:%M',  # e.g., 2025-02-20 11:00
        '%d/%m/%Y %H:%M'   # e.g., 20/02/2025 11:00
    ]
    for fmt in formats:
        try:
            return pd.to_datetime(date_str, format=fmt)
        except ValueError:
            continue
    return pd.NaT

# Apply the custom parsing
df2['VALID_UNTIL'] = df2['VALID_UNTIL'].astype(str).str.strip()
df2['VALID_UNTIL'] = df2['VALID_UNTIL'].apply(parse_date)

In [42]:
df2.VALID_UNTIL.value_counts(dropna=False)

VALID_UNTIL
2025-02-21 11:00:00    55
2025-02-20 11:00:00    39
2025-02-20 16:00:00    27
2025-02-25 16:00:00    15
Name: count, dtype: int64

In [43]:
df1.shape

(86, 23)

In [44]:
df2.shape

(136, 15)

# Combining both Dataframes

In [45]:
df_combined = pd.concat([df1, df2], axis=0, ignore_index=True)
df_combined.shape

(222, 34)

In [46]:
df_combined

,FACTORY_QUALITY,ORDER_GRADE_TEXT,NOMINAL_THICKNESS_MM,WIDTH_MM,LENGTH_MM,MASS_MIN_KG,CLUSTER,SI_CONTENT,MN_CONTENT,P_CONTENT,...,ORDER_ID,SITE,MATERIAL_NAME,MATERIAL_NUMBER,MATERIAL_QUALITY_NORM,DEFECT_NOTES,INCO_TERM,BUY_NOW_EUR_PER_TON,MIN/MAX_BID_EUR_PER_TON,VALID_UNTIL
0,G2UB5,SZBS800,320.000,856.0,787.0,16.490,WB-G,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,G2UJ5,SZBS800,339.000,918.0,707.0,17.160,WB-G,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,C3318,LICRO 500,452.000,1839.0,300.0,18.700,WB-U,0.2540,1.2780,0.0080,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,C3U15,S380MC mod. 4,532.000,1160.0,461.0,22.011,WB-U,0.2250,1.0630,0.0100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,G3UB5,SZBE800,451.000,727.2,557.0,14.020,Spaltband,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,NaN,NaN,0.800,1385.0,NaN,4580.000,NaN,NaN,NaN,NaN,...,436737.0,1 company gmbh,NaN,1.0873,NaN,DC06 / D2A ZUB,FCA,600.0,570.0,2025-02-20 11:00:00
218,NaN,NaN,11.859,1509.0,3008.0,2091.000,NaN,NaN,NaN,NaN,...,436765.0,1 company gmbh,S235JR,1.0038,DIN EN 10025,DEKL-S235JR / D2A EID,FCA,600.0,NaN,2025-02-20 11:00:00
219,NaN,NaN,0.712,1432.0,NaN,3160.000,NaN,NaN,NaN,NaN,...,436283.0,1 company gmbh,CR180BH,NaN,VDA 239-100,CR180BHZM40/40-E ZM 90 MC OL / D2A VMB,FCA,NaN,490.0,2025-02-20 16:00:00
220,NaN,NaN,12.008,1507.0,2506.0,3541.000,NaN,NaN,NaN,NaN,...,436626.0,1 company gmbh,NaN,1.0045,DIN EN 10025,NaN,FCA,640.0,610.0,2025-02-20 11:00:00
221,NaN,NaN,3.628,1256.0,2256.0,721.000,NaN,NaN,NaN,NaN,...,436521.0,1 company gmbh,S23SJR,1.0038,DIN EN 10025,NaN,FCA,NaN,550.0,2025-02-21 11:00:00

# Coloumn SITE -> CUSTOMER_NAME

The Site column has just one value in df2 and none in df1 so lets use that as a company name.

In [ ]:
df_combined['SITE'] = df_combined['SITE'].replace({'1 company gmbh': 'company 2'})
df_combined['SITE'].fillna('company 1',inplace=True)

In [49]:
df_combined.rename(columns={'SITE': 'CUSTOMER_NAME'}, inplace=True)

# Reordering the Columns with common columns at first

In [50]:
column_order = ['CUSTOMER_NAME', 'NOMINAL_THICKNESS_MM', 'WIDTH_MM', 'LENGTH_MM', 'MASS_MIN_KG'] + \
               [col for col in df_combined.columns if col not in ['CUSTOMER_NAME', 'NOMINAL_THICKNESS_MM',
                                                                  'WIDTH_MM', 'LENGTH_MM', 'MASS_MIN_KG']]

df_combined = df_combined[column_order]

In [51]:
df_combined

,CUSTOMER_NAME,NOMINAL_THICKNESS_MM,WIDTH_MM,LENGTH_MM,MASS_MIN_KG,FACTORY_QUALITY,ORDER_GRADE_TEXT,CLUSTER,SI_CONTENT,MN_CONTENT,...,PRODUCT_TYPE,ORDER_ID,MATERIAL_NAME,MATERIAL_NUMBER,MATERIAL_QUALITY_NORM,DEFECT_NOTES,INCO_TERM,BUY_NOW_EUR_PER_TON,MIN/MAX_BID_EUR_PER_TON,VALID_UNTIL
0,company 1,320.000,856.0,787.0,16.490,G2UB5,SZBS800,WB-G,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,company 1,339.000,918.0,707.0,17.160,G2UJ5,SZBS800,WB-G,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,company 1,452.000,1839.0,300.0,18.700,C3318,LICRO 500,WB-U,0.2540,1.2780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,company 1,532.000,1160.0,461.0,22.011,C3U15,S380MC mod. 4,WB-U,0.2250,1.0630,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,company 1,451.000,727.2,557.0,14.020,G3UB5,SZBE800,Spaltband,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,company 2,0.800,1385.0,NaN,4580.000,NaN,NaN,NaN,NaN,NaN,...,COIL_STRIP,436737.0,NaN,1.0873,NaN,DC06 / D2A ZUB,FCA,600.0,570.0,2025-02-20 11:00:00
218,company 2,11.859,1509.0,3008.0,2091.000,NaN,NaN,NaN,NaN,NaN,...,SHEET,436765.0,S235JR,1.0038,DIN EN 10025,DEKL-S235JR / D2A EID,FCA,600.0,NaN,2025-02-20 11:00:00
219,company 2,0.712,1432.0,NaN,3160.000,NaN,NaN,NaN,NaN,NaN,...,COIL_STRIP,436283.0,CR180BH,NaN,VDA 239-100,CR180BHZM40/40-E ZM 90 MC OL / D2A VMB,FCA,NaN,490.0,2025-02-20 16:00:00
220,company 2,12.008,1507.0,2506.0,3541.000,NaN,NaN,NaN,NaN,NaN,...,SHET,436626.0,NaN,1.0045,DIN EN 10025,NaN,FCA,640.0,610.0,2025-02-20 11:00:00
221,company 2,3.628,1256.0,2256.0,721.000,NaN,NaN,NaN,NaN,NaN,...,NaN,436521.0,S23SJR,1.0038,DIN EN 10025,NaN,FCA,NaN,550.0,2025-02-21 11:00:00

# Futher Exploration

The datasets seem to represent different aspects of raw materials, df1 is material property-focused, while df2 is order/transaction-focused


Although few columns have just few numerical data like the content of material but I still dont feel right to remove it. if it was for training some machine learning model I could go ahead but at present with given information, just to create a common inventory dataset I would prefer to keep it.